/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skydrm_sdk_nxl_NxlFileHandler */

#ifndef _Included_com_skydrm_sdk_nxl_NxlFileHandler
#define _Included_com_skydrm_sdk_nxl_NxlFileHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skydrm_sdk_nxl_NxlFileHandler
 * Method:    isMatchNxlFmt
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_isMatchNxlFmt
        (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     com_skydrm_sdk_nxl_NxlFileHandler
 * Method:    convertToNxlFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_convertToNxlFile
        (JNIEnv *, jclass, jstring, jstring, jstring, jbyteArray, jboolean);

/*
 * Class:     com_skydrm_sdk_nxl_NxlFileHandler
 * Method:    decryptToNormalFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_decryptToNormalFile
        (JNIEnv *, jclass, jstring, jstring, jbyteArray, jboolean);

/*
 * Class:     com_skydrm_sdk_nxl_NxlFileHandler
 * Method:    extractInfoFromNxlFile
 * Signature: (Ljava/lang/String;[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_extractInfoFromNxlFile
        (JNIEnv *, jclass, jstring, jbyteArray, jbyteArray);

/*
 * Class:     com_skydrm_sdk_nxl_NxlFileHandler
 * Method:    extractFingerPrint
 * Signature: (Ljava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_extractFingerPrint
        (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     com_skydrm_sdk_nxl_NxlFileHandler
 * Method:    calcHmacSha256
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_calcHmacSha256
        (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_skydrm_sdk_nxl_NxlFileHandler
 * Method:    sectionInfo
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_sectionInfo
        (JNIEnv *, jclass, jstring, jstring, jboolean, jbyteArray, jbyteArray);

JNIEXPORT jboolean JNICALL Java_com_skydrm_sdk_nxl_NxlFileHandler_readSection
        (JNIEnv *, jclass, jstring, jstring, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
